/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FetchOptions {
  userAgent?: string
}
export declare function fetchUrl(url: string, opts?: FetchOptions | undefined | null): Promise<Response>
export declare class Response {
  code: number
  body: string
  totalTime: number
  constructor(code: number, body: string, totalTime: number)
}
