x-default: &default
  init: true
  network_mode: host
  volumes:
    - ./data:/mnt/appdata
  environment:
    - DATA_DIR=/mnt/appdata
    - CONCURRENCY
    - LIMIT
  restart: on-failure
  deploy:
    resources:
      limits:
        cpus: "1.0"
        memory: 2G

services:
  deno-fetch:
    <<: *default
    build: deno/fetch
  csharp:
    <<: *default
    build: csharp
  go-http:
    <<: *default
    build: go/http
  java-http:
    <<: *default
    build: java/http
  kotlin:
    <<: *default
    build: kotlin
  node-fetch:
    <<: *default
    build: node/fetch
  node-puppeteer:
    <<: *default
    build: node/puppeteer
  node-reqwest:
    <<: *default
    build: node/reqwest
  python-aiohttp:
    <<: *default
    build: python/aiohttp
  ruby-async-http:
    <<: *default
    build: ruby/async-http
  rust-reqwest:
    <<: *default
    build: rust/reqwest
