x-default: &default
  entrypoint: "timeout ${DURATION:-600}"
  init: true
  network_mode: host
  environment:
    - CONCURRENCY
    - REQUEST_TIMEOUT=5
    - USER_AGENT=http-clients-test

services:
  bun:
    <<: *default
    build: lib/bun
    command: ["bun", "run", "main.js"]
  deno:
    <<: *default
    build: lib/deno
    command: [ "deno", "run", "--allow-env", "--allow-net", "main.js" ]
  dotnet:
    <<: *default
    build: lib/dotnet
    command: [ "dotnet", "dotnet.dll" ]
  go:
    <<: *default
    build: lib/go
    command: [ "/bin/run" ]
  java:
    <<: *default
    build: lib/java
    command: [ "java", "-Xmx1G", "Main" ]
  node-fetch:
    <<: *default
    build: lib/node/fetch
    command: [ "node", "main.js" ]
  node-puppeteer:
    <<: *default
    build: lib/node/puppeteer
  node-undici-request:
    <<: *default
    build: lib/node/undici-request
    command: [ "node", "main.js" ]
  node-reqwest:
    <<: *default
    build: lib/node/reqwest
    command: [ "node", "main.js" ]
  python-aiohttp:
    <<: *default
    build: lib/python/aiohttp
    command: [ "python", "main.py" ]
  ruby-async:
    <<: *default
    build: lib/ruby/async
    command: [ "ruby", "main.rb" ]
  rust-reqwest:
    <<: *default
    build: lib/rust/reqwest
    command: ["/bin/run"]
