x-default: &default
  entrypoint: "timeout ${DURATION:-600}"
  init: true
  network_mode: host
  environment:
    - CONCURRENCY
    - REQUEST_TIMEOUT=5
    - USER_AGENT=http-clients-test

services:
  bun:
    <<: *default
    build: bun
    command: ["bun", "run", "main.js"]
  deno:
    <<: *default
    build: deno
    command: [ "deno", "run", "--allow-env", "--allow-net", "main.js" ]
  dotnet:
    <<: *default
    build: dotnet
    command: [ "dotnet", "dotnet.dll" ]
  go:
    <<: *default
    build: go
    command: [ "/bin/run" ]
  java-http:
    <<: *default
    build: java/http
    command: [ "java", "-Xmx1G", "Main" ]
  kotlin:
    <<: *default
    build: kotlin
    command: [ "java", "-Xmx1G", "-jar", "crawler.jar" ]
  node-fetch:
    <<: *default
    build: node/fetch
    command: [ "node", "main.js" ]
  node-puppeteer:
    <<: *default
    build: node/puppeteer
  node-reqwest:
    <<: *default
    build: node/reqwest
    command: [ "node", "main.js" ]
  python-aiohttp:
    <<: *default
    build: python/aiohttp
    command: [ "python", "main.py" ]
  ruby-async:
    <<: *default
    build: ruby/async
    command: [ "ruby", "main.rb" ]
  rust-reqwest:
    <<: *default
    build: rust/reqwest
    command: ["/bin/run"]
