x-default: &default
  init: true
  network_mode: host
  volumes:
    - ./data:/mnt/appdata
  environment:
    - DATA_DIR=/mnt/appdata
  restart: on-failure

services:
  deno-fetch:
    <<: *default
    build: deno/fetch
  csharp:
    <<: *default
    build: csharp
  go-http:
    <<: *default
    build: go/http
  node-fetch:
    <<: *default
    build: node/fetch
  python-aiohttp:
    <<: *default
    build: python/aiohttp
  ruby-async-http:
    <<: *default
    build: ruby/async-http
  rust-reqwest:
    <<: *default
    build: rust/reqwest
