x-default: &default
  entrypoint: "timeout ${DURATION:-600}"
  network_mode: host
  environment:
    - CONCURRENCY
    - REQUEST_TIMEOUT=5
    - USER_AGENT=http-clients-test
  deploy:
    resources:
      limits:
        cpus: "1.0"
        memory: 2G

services:
  bun-fetch:
    <<: *default
    build: bun/fetch
  deno-fetch:
    <<: *default
    build: deno/fetch
    command: [ "deno", "run", "--allow-env", "--allow-net", "--unstable-http", "main.js" ]
  csharp:
    <<: *default
    build: csharp
    command: [ "dotnet", "csharp.dll" ]
  go-http:
    <<: *default
    build: go/http
    command: [ "/bin/run" ]
  java-http:
    <<: *default
    build: java/http
    command: [ "java", "-Xmx1G", "Main" ]
  kotlin:
    <<: *default
    build: kotlin
    command: [ "java", "-Xmx1G", "-jar", "crawler.jar" ]
  node-fetch:
    <<: *default
    build: node/fetch
    command: [ "node", "main.js" ]
  node-puppeteer:
    <<: *default
    build: node/puppeteer
  node-reqwest:
    <<: *default
    build: node/reqwest
    command: [ "node", "main.js" ]
  python-aiohttp:
    <<: *default
    build: python/aiohttp
  ruby-async-http:
    <<: *default
    build: ruby/async-http
  rust-reqwest:
    <<: *default
    build: rust/reqwest
