[package]
name = "rust-reqwest"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
reqwest = { version = "0.12.5", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1.38.0", features = ["full"] }

[[bin]]
name = "crawl"
path = "crawl.rs"
