#!/usr/bin/env python3

import os
import sys
import asyncio
import aiohttp
from time import time

CONCURRENCY = int(os.environ.get('CONCURRENCY', 10))
REQUEST_TIMEOUT = int(os.environ.get('REQUEST_TIMEOUT', 5))
file_path = sys.argv[1] if len(sys.argv) > 1 else 'data/urls.txt'

with open(file_path, 'r') as file:
    urls = file.read().splitlines()

print(f"Starting crawl with {CONCURRENCY} concurrency")
print(f"Request timeout: {REQUEST_TIMEOUT}s")
print(f"Reading URLs from {file_path}")

headers = {
    'User-Agent': 'crawler-test',
    'Accept-Encoding': 'gzip, deflate, br'
}

conn = aiohttp.TCPConnector(limit=CONCURRENCY)
semaphore = asyncio.Semaphore(CONCURRENCY)

async def make_request(url):
    async with semaphore:
        start = time()

        timeout=aiohttp.ClientTimeout(total=REQUEST_TIMEOUT, connect=1, sock_connect=1, sock_read=REQUEST_TIMEOUT)

        async with aiohttp.ClientSession(headers=headers, timeout=timeout) as session:
            try:
                async with session.get(url) as response:
                    code = response.status
            except Exception as exc:
                code = exc.__class__.__name__
            finally:
                duration = time() - start
                print(f"{url} - {code} - {duration:.2f}s")
                return {'url': url, 'code': code, 'time': duration}

async def main():
    tasks = [make_request(url) for url in urls]

    results = await asyncio.gather(*tasks)

    aggregates = {}
    for result in results:
        code = result['code']
        aggregates[code] = aggregates.get(code, 0) + 1

    avg_time = sum(result['time'] for result in results) / len(results)
    median_time = sorted(result['time'] for result in results)[len(results) // 2]

    print(f"Average time: {avg_time * 1000:.2f}ms")
    print(f"Median time: {median_time * 1000:.2f}ms")
    print(f"Total URLs: {sum(aggregates.values())}")

    print(aggregates)

try:
    start = time()
    asyncio.run(main())
except Exception as exc:
    print(exc)
finally:
    print(f"Total time: {time() - start:.2f}s")